jv-multithreading-decrease-counter-hw
mate-academy/jv-multithreading-decrease-counter pull request #14
Opened 2021-11-02 22:27 UTC by lavrivskyi

Race condition fixed

2021-11-02 23:13 UTC, Evgen-Krasnenkov approved these changes

2021-11-04 09:35 UTC, Resci requested changes

2021-11-04 09:35 UTC, Resci commented on src/main/java/core/basesyntax/Counter.java
> +        synchronized (this) {
Достатньо вказати ключове слово `synchronized` в сигнатурі методу

2021-11-04 09:51 UTC, lavrivskyi commented on src/main/java/core/basesyntax/Counter.java
> +        synchronized (this) {
Fixed

2021-11-04 10:16 UTC, Resci approved these changes

2024-08-13 19:38 UTC, closed without merging